import './globals.css'
import { Toaster } from "./Toaster";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-violet-950 text-white">
        {children}
        <Toaster />
        </body>
    </html>
  )
}
